### ISSUE TITLE
Use consistent object keys in json alignment format

### ISSUE THREAD

**Issue by themikejr** [Clear-Bible/Alignments#1]
In the current JSON alignment format, a "link" (i.e. a single alignment instance) is modeled like so:

```json
{"01001001.1": {"WLC": ["010010010011"], "YLT": ["01001001001"], "meta": {"process": "manual"}}}
```

While this sample demonstrates a flexible data structure that I believe will support important features like many-to-many links, discontiguous tokens, and extensible metadata, there are some significant issues when it comes to consuming the data that are not necessary. 

Perhaps the most common pattern that I think will emerge is folks iterating through a list of links and accessing various attributes on the link to generate a UI, train a model, etc... The current data format requires one to know what the keys in the data are in order to access various fields on a link, e..g.

```python
for alignment in alignments:
  source_token_ids = alignment["WLC"]
  target_token_ids = alignment["YLT"]
  etc...
```

To write generic code that can process an arbitrary number of alignments, a programmer is required to write code that determines which corpora exist in the alignment and which is source/target. 

I don't think it's necessary to encode metadata into the data structure itself. I propose a more generic JSON data structure that would provide consistent object keys:

```json
{ "id": "01001001.1", "source_token_ids":  ["010010010011"], "target_token_ids": ["01001001001"], "meta": {"process": "manual"}}}
```

Corpus-level metadata could then be stored in JSON or another format that would describe each corpus's role (source, target, etc...).

Furthermore, we could refrain from using "source" and "target" terminology completely to enable alignments that include more than 2 corpora:

```json
{ "id": "01001001.1", "r0":  ["010010010011"], "r1": ["01001001002"], "r2": ["01001001003"] "meta": {"process": "manual"}}}
```

The latter approach is described well [here](https://github.com/unfoldingWord/wordMAP-usfm#alignment-json-data-structure). I like that this format includes alignment metadata in JSON, so all relevant data is included in a single source file.

**Comment by themikejr** [comment]
Out of those I think I like `source_ids` and `target_ids`.

@sboisen how do you feel about the more flexible `r0` (resource #0), `r1`, `r2` etc...?

**Comment by sboisen** [comment]
(Oops, forgot to hit 'send' on this :-/)

> Furthermore, we could refrain from using "source" and "target" terminology completely to enable alignments that include more than 2 corpora:
> { "id": "01001001.1", "r0":  ["010010010011"], "r1": ["01001001002"], "r2": ["01001001003"] "meta": {"process": "manual"}}}
> The latter approach is described well [here](https://github.com/unfoldingWord/wordMAP-usfm#alignment-json-data-structure). I like that this format includes alignment metadata in JSON, so all relevant data is included in a single source file.

While i like the generality of supporting multiple alignments, do we (or uW) actually have data like this? And why "r"? This seems a little harder to interpret, though it's a small point. 

I get the benefit of all metadata in one file. The current approach is a separate .toml file (which seems like a friendlier format to me), held together with the alignment data through a common directory. But maybe we shoul reconsider.

**Comment by sboisen** [comment]
Updated alignments for ESV and LEB instantiate these suggestions: i'll be using this going forward.
Discussion is on-going about the reference system (BBCCCVVVWWWP or variants): let's call that a separate issue, along with whether we should incorporate the metadata (currently in a separate TOML file) into the alignment JSON. 
Closing this issue for now.
